version: "3.9"

services:
  llm_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm_server
    restart: unless-stopped
    ports:
      - "8090:8000"
    volumes:
      - ./models:/app/models
      - ./.env:/app/.env
      - ./api_keys.json:/app/api_keys.json

    env_file:
      - .env

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    runtime: nvidia
