# docker-compose.yaml
services:
  llm_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm_server
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./.env:/app/.env

    environment:
      MODEL_PATH: "/app/models/gemma-3-4b-it-q4_0.gguf"
      ALLOWED_API_KEYS: "sk-local-key-dev"
